# 1.2.1 Пример

Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [1]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


# 1.2.2 Пример

Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [2]:
a = np.zeros(10)
b = np.ones(10"}=-'[;p]')
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


# 1.2.3 Пример

Создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение.

In [3]:
Z = np.random.random((10,10))
Zmin, Zmax, Zmin = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmin)

0.5077720396210182 0.9950703319986344 0.5077720396210182


# 1.2.4 Пример

Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами

In [4]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 1.2.5 Пример

Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [5]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


# 1.2.6 Пример

Отсортировать массив

In [6]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


# 1.3.1 Задание

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [7]:
A = np.array([[0, 1, 0, 1, 0, 1, 0, 1],
            [1, 0, 1, 0, 1, 0, 1, 0],
            [0, 1, 0, 1, 0, 1, 0, 1],
            [1, 0, 1, 0, 1, 0, 1, 0],
            [0, 1, 0, 1, 0, 1, 0, 1],
            [1, 0, 1, 0, 1, 0, 1, 0],
            [0, 1, 0, 1, 0, 1, 0, 1],
            [1, 0, 1, 0, 1, 0, 1, 0]])
B = np.arange(64).reshape(8, 8)
for i in range(8):
    for j in range(8):
        if i % 2 == 0:
            B[i][j] = int(j % 2 == 1)
        else:
            B[i][j] = int(j % 2 == 0)
print("Первый способ","\n", A)
print("Второй способ","\n", B)

Первый способ 
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Второй способ 
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 1.3.2 Задание

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange

In [8]:
B = np.arange(5)
C = np.vstack((B,B,B,B,B)) #соединение строк в матрицу
print("Первый способ","\n",C)
D = np.arange(25).reshape(5,5)
D[[1,2,3,4]] = D[[0,0,0,0]]
print("Второй способ","\n",D)
Z = np.zeros((5,5))
Z += np.arange(5)
print("Третий способ","\n",Z)

Первый способ 
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
Второй способ 
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
Третий способ 
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# 1.3.3 Задание

Создать массив 3x3x3 со случайными значениями

In [9]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.09002548 0.8656856  0.62630912]
  [0.26464701 0.10496895 0.93722985]
  [0.47636596 0.16177107 0.49579409]]

 [[0.95491564 0.39382417 0.47729601]
  [0.91646051 0.08528003 0.48441721]
  [0.31202858 0.78300861 0.42260721]]

 [[0.21255552 0.31956315 0.4112835 ]
  [0.63337952 0.37352295 0.82375491]
  [0.36075529 0.25643086 0.01708677]]]


# 1.3.4 Задание

Создать матрицу с 0 внутри, и 1 на границах.

In [10]:
B = np.arange(64).reshape(8, 8)
for i in range(8):
    for j in range(8):
        if i==0 or j==0 or i==7 or j==7:
            B[i][j] = 1
        else:
            B[i][j] = 0
print(B)
C=np.ones([4,4],dtype = int)
C[1:-1,1:-1]=0
print("Второй способ","\n", C)


[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]
Второй способ 
 [[1 1 1]
 [1 0 1]
 [1 1 1]]


# 1.3.5 Задание

Создайте массив и отсортируйте его по убыванию.

In [11]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.flip(np.sort(arr), 0))

[8 7 6 5 4 3 2 1]


# 1.3.6 Задание

Создайте матрицу, выведите ее форму, размер и размерность

In [12]:
A = np.arange(25).reshape(5,5)
print(A)
print("Form = ", A.shape)
print("Amount of axis = ", A.ndim)
print("Amount of elements = ", A.size)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Form =  (5, 5)
Amount of axis =  2
Amount of elements =  25


# 2.2.1 Пример

Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).

In [13]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])
s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])
print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


# 2.2.2 Пример

Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [14]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


# 2.2.3 Пример

Создайте новый фрейм данных.

In [15]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

# 2.2.4 Пример

Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [18]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

# 2.2.5 Пример 

Пронализировать характеристики фрейма данных.

In [19]:
dataframe.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [20]:
dataframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [21]:
dataframe.shape

(1313, 6)

In [22]:
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

# 2.2.6 Пример

Выберите индивидуальные данные или срезы фрейма данных.

In [23]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

# 2.2.7 Пример

Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.

In [24]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

# 2.3.1 Задание

Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [26]:
a = pd.Series([2, 4, 6, 8])
b = pd.Series([1, 3, 5, 7])

print(sum((a - b)**2)**0.5)

2.0


# 2.3.2 Задание

Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [27]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/birdkeeper_lungcancer.csv'
dataframe = pd.read_csv(url)
dataframe.head(1)

fm   ss    bk  ag  yr  cd          lc
0  Male  Low  Bird  37  19  12  LungCancer

# 2.3.3 Задание

Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [28]:
dataframe.head(3)

fm    ss      bk  ag  yr  cd          lc
0  Male   Low    Bird  37  19  12  LungCancer
1  Male   Low    Bird  41  22  15  LungCancer
2  Male  High  NoBird  43  19  15  LungCancer

In [29]:
dataframe.tail(4)

fm    ss      bk  ag  yr  cd        lc
143  Female  High  NoBird  63   0   0  NoCancer
144  Female   Low  NoBird  64  39  20  NoCancer
145  Female  High  NoBird  64   0   0  NoCancer
146  Female   Low  NoBird  65   7   2  NoCancer

In [30]:
dataframe.shape

(147, 7)

In [31]:
dataframe.describe()

ag         yr          cd
count  147.000000  147.00000  147.000000
mean    56.965986   27.85034   15.748299
std      7.348856   13.97569    9.703723
min     37.000000    0.00000    0.000000
25%     52.000000   20.00000   10.000000
50%     59.000000   30.00000   15.000000
75%     63.000000   39.00000   20.000000
max     67.000000   50.00000   45.000000

In [32]:
dataframe.iloc[100:107]

fm    ss      bk  ag  yr  cd        lc
100  Male   Low    Bird  63   0   0  NoCancer
101  Male  High  NoBird  63  41  20  NoCancer
102  Male   Low  NoBird  63  20  15  NoCancer
103  Male  High  NoBird  63  43  20  NoCancer
104  Male  High  NoBird  63  42  10  NoCancer
105  Male   Low  NoBird  64  41   6  NoCancer
106  Male  High  NoBird  64  39  25  NoCancer

In [33]:
dataframe[dataframe['yr'] == 27].head(2)

fm   ss      bk  ag  yr  cd          lc
40   Female  Low    Bird  49  27  20  LungCancer
130  Female  Low  NoBird  49  27  20    NoCancer

# 3.2.1 Пример

Прошкалируйте числовой признак в диапазон между двумя значениями.

In [34]:
# Загрузить библиотеки
import numpy as np
from sklearn import preprocessing

# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])

# # Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

#Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

# 3.2.2 Пример

Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [35]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])

# # Создать калибровщик
scaler = preprocessing.StandardScaler()

# Преобразовать признак
standardized = scaler.fit_transform(x)

# Показать признак
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [36]:
#Мы можем увидеть эффект стандартизации, обратившись к среднему
#значению и стандартному отклонению результата нашего решения:

print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


# 3.2.3 Пример

Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы.

In [37]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big', 'small','small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

# 3.3.1 Задание

Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [38]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing

scaler = MinMaxScaler()
scalerZ = preprocessing.StandardScaler()
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
dataframe.head(10)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa
5              5.4             3.9              1.7             0.4  setosa
6              4.6             3.4              1.4             0.3  setosa
7              5.0             3.4              1.5             0.2  setosa
8              4.4             2.9              1.4             0.2  setosa
9              4.9             3.1              1.5             0.1  setosa

In [39]:
dataframe[['sepal_length_cm']] = scaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe.head(10)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222             3.5              1.4             0.2  setosa
1         0.166667             3.0              1.4             0.2  setosa
2         0.111111             3.2              1.3             0.2  setosa
3         0.083333             3.1              1.5             0.2  setosa
4         0.194444             3.6              1.4             0.2  setosa
5         0.305556             3.9              1.7             0.4  setosa
6         0.083333             3.4              1.4             0.3  setosa
7         0.194444             3.4              1.5             0.2  setosa
8         0.027778             2.9              1.4             0.2  setosa
9         0.166667             3.1              1.5             0.1  setosa

In [40]:
dataframe[['sepal_width_cm']] = scalerZ.fit_transform(dataframe[['sepal_width_cm']])
dataframe.head(10)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa
5         0.305556        1.957669              1.7             0.4  setosa
6         0.083333        0.800654              1.4             0.3  setosa
7         0.194444        0.800654              1.5             0.2  setosa
8         0.027778       -0.356361              1.4             0.2  setosa
9         0.166667        0.106445              1.5             0.1  setosa

In [41]:
print("Среднее:", round(dataframe[['sepal_width_cm']].mean()))
print("Стандартное отклонение:", round(dataframe[['sepal_width_cm']].std()))

Среднее: sepal_width_cm   -0.0
dtype: float64
Стандартное отклонение: sepal_width_cm    1.0
dtype: float64
